import { PrismaClient } from '@prisma/client';
const p = new PrismaClient();

const clientId = '3e358a98-d548-4eeb-b113-15a882049e12';
const anjali   = 'c4971f5a-50f5-4e52-943d-fd4e52199158';
const rohan    = '916c5328-a654-4c55-a21a-27e9ac460400';
const proj1    = 'f77559f0-820f-4cb2-9f46-1b0df8e00bbb'; // Replenishment v2
const proj2    = '7f739716-4a00-43ed-8dc8-02c3c29b8b2c'; // Raw Material AI Pilot
const proj3    = '2c2c4bc4-20b2-4407-97c8-20c53959b8d2'; // SAP Integration
const ravi     = '68c43f1d-98c0-476b-8d8d-1f11b5a96e4f';
const arjun    = 'b2b5ecb2-5cc2-4c0d-b866-c3b751f2e937';
const kiran    = '44495d06-9409-47be-ac3f-931dd98ebc88';
const sneha    = '18667897-dd3f-438c-a505-2e36e470f4ff';

const now = new Date();
const ago = d => new Date(now - d * 86400000);

const issues = [
  // ── REPLENISHMENT PLANNING ──────────────────────────────────────────────────
  { title: 'Replenishment plan not recalculating after safety stock update', description: 'After updating safety stock levels for 15 SKUs in the RP module, the replenishment plan still shows old quantities. Manual refresh does not help.', category: 'BUG', priority: 'HIGH', status: 'OPEN', projectId: proj1, raisedById: anjali, assignedToId: ravi, createdAt: ago(5) },
  { title: 'Demand forecast showing negative values for seasonal SKUs', description: 'The RP module is generating negative demand forecasts for 8 seasonal personal care SKUs, causing incorrect reorder quantities sent to suppliers.', category: 'DATA_ACCURACY', priority: 'CRITICAL', status: 'IN_PROGRESS', projectId: proj1, raisedById: rohan, assignedToId: sneha, createdAt: ago(3) },
  { title: 'Reorder point calculation ignoring lead time buffer', description: 'Replenishment Planning calculates reorder points without the 3-day lead time buffer we configured two weeks ago. Orders are triggering too late.', category: 'BUG', priority: 'HIGH', status: 'RESOLVED', projectId: proj1, raisedById: anjali, assignedToId: ravi, createdAt: ago(15), resolvedAt: ago(10) },
  { title: 'RP module crashes when loading more than 200 SKUs', description: 'Loading the full SKU list (240 items) in the Replenishment Planning grid crashes the browser tab. Works fine with fewer than 200 SKUs.', category: 'PERFORMANCE', priority: 'HIGH', status: 'IN_PROGRESS', projectId: proj1, raisedById: rohan, assignedToId: kiran, createdAt: ago(4) },
  { title: 'Supplier allocation split not saving correctly', description: 'A 60/40 split between two suppliers for a SKU reverts to 100% primary supplier after saving in the RP module.', category: 'BUG', priority: 'MEDIUM', status: 'OPEN', projectId: proj1, raisedById: anjali, assignedToId: null, createdAt: ago(2) },
  { title: 'Bulk upload template for RP parameters throwing validation errors', description: 'The Excel bulk upload for replenishment parameters rejects valid entries with a generic validation error on row 23 onwards. Small uploads under 20 rows work fine.', category: 'BUG', priority: 'MEDIUM', status: 'ACKNOWLEDGED', projectId: proj1, raisedById: rohan, assignedToId: sneha, createdAt: ago(6) },
  { title: 'RP dashboard KPI tiles not loading after login', description: 'KPI tiles on the Replenishment Planning dashboard (Total Coverage, Reorder Alerts, Supplier Fill Rate) show a spinner indefinitely after login.', category: 'BUG', priority: 'HIGH', status: 'OPEN', projectId: proj1, raisedById: anjali, assignedToId: null, createdAt: ago(1) },
  { title: 'Auto-replenishment orders triggering on public holidays', description: 'The system generates automated purchase orders on national holidays (April 14). Suppliers cannot process these orders.', category: 'BUG', priority: 'MEDIUM', status: 'RESOLVED', projectId: proj1, raisedById: rohan, assignedToId: ravi, createdAt: ago(20), resolvedAt: ago(14) },
  { title: 'Coverage days calculation wrong for fast-moving SKUs', description: 'Coverage days for our top 10 fast-moving SKUs shows 45 days but actual stock is only 12 days. The formula appears to use monthly instead of weekly consumption.', category: 'DATA_ACCURACY', priority: 'HIGH', status: 'IN_PROGRESS', projectId: proj1, raisedById: anjali, assignedToId: sneha, createdAt: ago(7) },
  { title: 'Minimum order quantity constraints ignored in RP plan', description: 'MOQ constraints set for 5 suppliers are being ignored. The system suggests order quantities below the agreed MOQ.', category: 'BUG', priority: 'MEDIUM', status: 'OPEN', projectId: proj1, raisedById: rohan, assignedToId: null, createdAt: ago(3) },
  { title: 'Need ability to lock approved replenishment lines', description: 'Once a planner approves a replenishment line, other users should not be able to edit it. Currently anyone can modify approved lines causing discrepancies.', category: 'FEATURE_REQUEST', priority: 'MEDIUM', status: 'OPEN', projectId: proj1, raisedById: anjali, assignedToId: null, createdAt: ago(8) },
  { title: 'Replenishment plan export missing supplier lead time column', description: 'The Excel export from the RP module does not include the Supplier Lead Time column needed for our weekly S&OP meeting report.', category: 'FEATURE_REQUEST', priority: 'LOW', status: 'ACKNOWLEDGED', projectId: proj1, raisedById: rohan, assignedToId: kiran, createdAt: ago(10) },
  { title: 'Add email alert when stock falls below safety stock', description: 'We need automated email alerts sent to our supply chain team when any SKU falls below configured safety stock. Currently we check the dashboard manually.', category: 'FEATURE_REQUEST', priority: 'MEDIUM', status: 'OPEN', projectId: proj1, raisedById: anjali, assignedToId: null, createdAt: ago(5) },

  // ── PRODUCTION PLANNING ─────────────────────────────────────────────────────
  { title: 'Production plan not considering machine downtime schedule', description: 'The PP module schedules production runs during the planned maintenance window (Saturdays 8-12am) that we configured 2 weeks ago. The downtime calendar is ignored.', category: 'BUG', priority: 'HIGH', status: 'OPEN', projectId: proj3, raisedById: anjali, assignedToId: arjun, createdAt: ago(4) },
  { title: 'Batch size rounding causing material wastage in PP', description: 'Production Planning rounds batch sizes down instead of up, causing insufficient material allocation for some batches and incomplete production runs.', category: 'BUG', priority: 'HIGH', status: 'IN_PROGRESS', projectId: proj3, raisedById: rohan, assignedToId: ravi, createdAt: ago(6) },
  { title: 'PP Gantt chart not rendering for more than 4 weeks', description: 'Viewing the production Gantt chart for a 6 or 8-week horizon fails with a blank screen. The 4-week view works fine.', category: 'PERFORMANCE', priority: 'MEDIUM', status: 'RESOLVED', projectId: proj3, raisedById: anjali, assignedToId: kiran, createdAt: ago(18), resolvedAt: ago(12) },
  { title: 'Changeover time between product lines not calculated in PP', description: 'The PP module does not account for the 2-hour changeover time when switching between toothpaste and shampoo lines on Line 3, causing scheduling conflicts.', category: 'BUG', priority: 'HIGH', status: 'ACKNOWLEDGED', projectId: proj3, raisedById: rohan, assignedToId: sneha, createdAt: ago(3) },
  { title: 'PP plan showing overcapacity alerts at 78% utilisation incorrectly', description: 'Line 2 is flagged as overcapacity at 78% utilisation but our threshold is 85%. The system appears to be using wrong capacity parameters.', category: 'DATA_ACCURACY', priority: 'MEDIUM', status: 'OPEN', projectId: proj3, raisedById: anjali, assignedToId: null, createdAt: ago(2) },
  { title: 'Production order quantities doubling on page refresh', description: 'After editing a production order quantity and saving, a page refresh doubles the quantity. This has caused over-planning for 3 SKUs this week.', category: 'BUG', priority: 'CRITICAL', status: 'IN_PROGRESS', projectId: proj3, raisedById: rohan, assignedToId: ravi, createdAt: ago(1) },
  { title: 'Finished goods inventory not updating after production confirmation', description: 'After confirming a production order as complete in PP, finished goods inventory balance is not updated. The stock ledger still shows pre-production figures.', category: 'BUG', priority: 'HIGH', status: 'OPEN', projectId: proj3, raisedById: anjali, assignedToId: null, createdAt: ago(2) },
  { title: 'PP module showing 404 error for production planner accounts', description: 'Two production planners with accounts created last week get a 404 error when accessing the PP module. Admin accounts work fine.', category: 'ACCESS_SECURITY', priority: 'HIGH', status: 'RESOLVED', projectId: proj3, raisedById: anjali, assignedToId: sneha, createdAt: ago(12), resolvedAt: ago(8) },
  { title: 'Cannot assign multiple work centres to a single production order', description: 'The system only allows one work centre per production order. For blending operations we need to assign Line 1 and the mixing station simultaneously.', category: 'FEATURE_REQUEST', priority: 'MEDIUM', status: 'OPEN', projectId: proj3, raisedById: rohan, assignedToId: null, createdAt: ago(5) },
  { title: 'Production plan PDF export layout broken', description: 'The PDF export of the weekly production plan has overlapping columns in the schedule view. Started after last week update. Excel export is fine.', category: 'BUG', priority: 'LOW', status: 'RESOLVED', projectId: proj3, raisedById: rohan, assignedToId: kiran, createdAt: ago(22), resolvedAt: ago(17) },
  { title: 'Shift schedule not visible to shift supervisors', description: 'Shift supervisors can log in but cannot see the shift schedule view. The shift allocation tab is missing from their role despite correct permissions.', category: 'ACCESS_SECURITY', priority: 'MEDIUM', status: 'ACKNOWLEDGED', projectId: proj3, raisedById: anjali, assignedToId: arjun, createdAt: ago(4) },

  // ── RAW MATERIAL PLANNING ───────────────────────────────────────────────────
  { title: 'BOM explosion not picking up latest approved BOM version', description: 'RMP is using BOM version 3.1 for material requirements calculation, but version 3.2 was approved on April 10 with updated polymer quantities.', category: 'DATA_ACCURACY', priority: 'CRITICAL', status: 'IN_PROGRESS', projectId: proj2, raisedById: anjali, assignedToId: sneha, createdAt: ago(3) },
  { title: 'Raw material stock reconciliation showing 15% discrepancy', description: 'System stock for Sodium Lauryl Sulphate shows 12,000 kg but physical count shows 10,200 kg. Discrepancy started after the April 5 data import.', category: 'DATA_ACCURACY', priority: 'HIGH', status: 'OPEN', projectId: proj2, raisedById: rohan, assignedToId: null, createdAt: ago(5) },
  { title: 'Material requirements not netting open purchase orders', description: 'RMP calculates gross material requirements without netting the 3 open POs with Godrej Chemicals, causing duplicate purchase requisitions.', category: 'BUG', priority: 'HIGH', status: 'IN_PROGRESS', projectId: proj2, raisedById: anjali, assignedToId: ravi, createdAt: ago(4) },
  { title: 'Approved vendor list not filtering in material sourcing screen', description: 'The vendor dropdown when raising a material purchase request shows all vendors including unapproved ones. Should only show approved vendors for that material.', category: 'BUG', priority: 'MEDIUM', status: 'OPEN', projectId: proj2, raisedById: rohan, assignedToId: null, createdAt: ago(6) },
  { title: 'Material shelf life expiry alerts not triggering', description: 'Expiry alerts configured for fragrance materials with 6-month shelf life failed to trigger for Batch FR-2024-089 which expired April 12.', category: 'BUG', priority: 'HIGH', status: 'ACKNOWLEDGED', projectId: proj2, raisedById: anjali, assignedToId: sneha, createdAt: ago(9) },
  { title: 'Material availability report taking 4+ minutes to load in RMP', description: 'The material availability report in RMP takes over 4 minutes to generate for our full raw material list. Last month it was under 30 seconds.', category: 'PERFORMANCE', priority: 'HIGH', status: 'OPEN', projectId: proj2, raisedById: rohan, assignedToId: kiran, createdAt: ago(2) },
  { title: 'Substitute material mapping not triggering during shortage', description: 'Substitute materials configured for 4 critical raw materials are not being activated when primary material stock hits zero in the plan.', category: 'BUG', priority: 'CRITICAL', status: 'IN_PROGRESS', projectId: proj2, raisedById: anjali, assignedToId: ravi, createdAt: ago(2) },
  { title: 'Goods receipt entry rejected with duplicate transaction error', description: 'Recording a goods receipt for PO-2025-0412 gives a duplicate transaction error even though this is the first receipt entry for this PO.', category: 'BUG', priority: 'HIGH', status: 'RESOLVED', projectId: proj2, raisedById: rohan, assignedToId: arjun, createdAt: ago(16), resolvedAt: ago(11) },
  { title: 'Material cost variance report not reflecting updated standard costs', description: 'Standard costs updated for 22 raw materials on April 1 are not reflected in the cost variance report, which still uses last year values.', category: 'DATA_ACCURACY', priority: 'HIGH', status: 'OPEN', projectId: proj2, raisedById: anjali, assignedToId: null, createdAt: ago(7) },
  { title: 'RMP dashboard crashes when switching between Plant A and Plant B', description: 'Switching from Plant A to Plant B using the plant selector in RMP crashes the dashboard with a white screen.', category: 'BUG', priority: 'HIGH', status: 'IN_PROGRESS', projectId: proj2, raisedById: rohan, assignedToId: kiran, createdAt: ago(3) },
  { title: 'Batch traceability report missing supplier lot numbers', description: 'The batch traceability report for fragrance materials does not show supplier lot numbers, which we need for our FDA audit next month.', category: 'DATA_ACCURACY', priority: 'HIGH', status: 'ACKNOWLEDGED', projectId: proj2, raisedById: anjali, assignedToId: sneha, createdAt: ago(5) },
  { title: 'Bulk import for raw material masters rejecting decimal values', description: 'The bulk import template for raw material masters rejects rows where unit cost has decimal values (e.g. 45.50 per kg). Only whole numbers are accepted.', category: 'BUG', priority: 'MEDIUM', status: 'RESOLVED', projectId: proj2, raisedById: rohan, assignedToId: ravi, createdAt: ago(25), resolvedAt: ago(19) },

  // ── PLATFORM / CROSS-MODULE ─────────────────────────────────────────────────
  { title: 'Planning dashboard not loading on Safari browser', description: 'The main planning dashboard shows a blank white page on Safari (MacBook). Chrome and Edge work fine. Affects our CFO and VP Operations.', category: 'BUG', priority: 'HIGH', status: 'OPEN', projectId: proj1, raisedById: anjali, assignedToId: null, createdAt: ago(4) },
  { title: 'User session timing out after 10 minutes of inactivity', description: 'Users are being logged out after 10 minutes of inactivity. Our team leaves reports open during 30-45 minute meetings. Session timeout should be at least 60 minutes.', category: 'ACCESS_SECURITY', priority: 'MEDIUM', status: 'RESOLVED', projectId: proj1, raisedById: rohan, assignedToId: arjun, createdAt: ago(30), resolvedAt: ago(22) },
  { title: 'Monthly S&OP report taking 8+ minutes to generate', description: 'The monthly S&OP consolidated report combining RP, PP and RMP data for senior leadership now takes over 8 minutes. Previously it completed in under 2 minutes.', category: 'PERFORMANCE', priority: 'HIGH', status: 'IN_PROGRESS', projectId: proj3, raisedById: anjali, assignedToId: kiran, createdAt: ago(5) },
  { title: 'Cannot download attachments from resolved tickets', description: 'Downloading attachments from tickets in Resolved status returns a 403 Forbidden error. Attachments on open tickets download fine.', category: 'ACCESS_SECURITY', priority: 'LOW', status: 'OPEN', projectId: proj2, raisedById: rohan, assignedToId: null, createdAt: ago(3) },
  { title: 'Notification emails landing in spam for all Colgate users', description: 'All system notification emails (ticket updates, alerts, approvals) are landing in spam for all our users. Started 10 days ago. We are missing critical alerts.', category: 'BUG', priority: 'HIGH', status: 'ACKNOWLEDGED', projectId: proj1, raisedById: anjali, assignedToId: sneha, createdAt: ago(10) },
  { title: 'CSV export corrupting special characters in product names', description: 'Exporting planning data to CSV corrupts special characters in product names (e.g. accents). Affects our international product SKUs.', category: 'BUG', priority: 'MEDIUM', status: 'RESOLVED', projectId: proj2, raisedById: rohan, assignedToId: ravi, createdAt: ago(28), resolvedAt: ago(20) },
  { title: 'Audit log not recording changes made via bulk upload', description: 'Changes made through the bulk upload feature are not appearing in the audit log. Only manual in-app edits are logged. This is a compliance requirement.', category: 'BUG', priority: 'HIGH', status: 'OPEN', projectId: proj3, raisedById: anjali, assignedToId: null, createdAt: ago(6) },
  { title: '2FA OTP always invalid for client admin accounts', description: 'OTP sent to email for 2FA-enabled admin accounts always shows as invalid when entered. Regular accounts without 2FA work fine.', category: 'ACCESS_SECURITY', priority: 'HIGH', status: 'IN_PROGRESS', projectId: proj1, raisedById: anjali, assignedToId: arjun, createdAt: ago(4) },
  { title: 'Plan comparison view highlighting unchanged values incorrectly', description: 'The side-by-side plan comparison feature marks some unchanged values as changed (highlighted in red), making it very hard to identify actual differences.', category: 'BUG', priority: 'MEDIUM', status: 'OPEN', projectId: proj3, raisedById: rohan, assignedToId: null, createdAt: ago(5) },
  { title: 'Scheduled report email delivery stopped since April 14', description: 'The weekly automated replenishment summary email to our distribution list stopped on April 14. The schedule shows as active in system settings.', category: 'BUG', priority: 'HIGH', status: 'ACKNOWLEDGED', projectId: proj1, raisedById: anjali, assignedToId: ravi, createdAt: ago(7) },
  { title: 'Planning dashboard layout broken on iOS mobile', description: 'The planning dashboard on iPhone 14 (iOS 17) has overlapping text and broken layout. Our field team uses mobile to check coverage days and alerts at plant.', category: 'BUG', priority: 'MEDIUM', status: 'OPEN', projectId: proj1, raisedById: rohan, assignedToId: null, createdAt: ago(3) },
  { title: 'User role change not taking effect until next login', description: 'Updating a user from Viewer to Planner role in the admin panel does not reflect until the user logs out and back in. Should apply immediately.', category: 'ACCESS_SECURITY', priority: 'LOW', status: 'RESOLVED', projectId: proj2, raisedById: anjali, assignedToId: kiran, createdAt: ago(35), resolvedAt: ago(28) },
  { title: 'Nightly ERP sync hitting API rate limits causing 30% failure', description: 'Our ERP sync job is hitting API rate limit errors (HTTP 429) during the nightly data sync window, causing approximately 30% of records to fail each night.', category: 'PERFORMANCE', priority: 'HIGH', status: 'IN_PROGRESS', projectId: proj3, raisedById: anjali, assignedToId: ravi, createdAt: ago(6) },
  { title: 'Forecast Accuracy KPI tile showing NaN on dashboard', description: 'The Forecast Accuracy KPI tile on the main dashboard displays NaN instead of a percentage value. Started after the April 15 system update.', category: 'BUG', priority: 'MEDIUM', status: 'OPEN', projectId: proj1, raisedById: rohan, assignedToId: null, createdAt: ago(8) },
  { title: 'SSO login failing intermittently for 3 Colgate users', description: 'Three users experience intermittent SSO failures — they are redirected back to the login page after successful SSO authentication, roughly 1 in 5 attempts.', category: 'ACCESS_SECURITY', priority: 'HIGH', status: 'RESOLVED', projectId: proj3, raisedById: anjali, assignedToId: sneha, createdAt: ago(14), resolvedAt: ago(7) },
];

let count = 0;
for (const issue of issues) {
  await p.issue.create({ data: { ...issue, clientId, slaBreached: false, slaBreachRisk: false, escalated: false } });
  count++;
}
console.log('Inserted:', count, 'issues');
await p.$disconnect();
